# This action is provided for backward-compatibility purposes; do not use it
# for new projects. Instead, use `upload-openapi-spec-action/build`.

name: Stainless — Build SDK
description: Build SDKs
branding:
  icon: book-open
  color: green
runs:
  using: node20
  main: dist/index.js
inputs:
  stainless_api_key:
    description: >-
      Stainless API key. Optional for GitHub Actions (will use OIDC authentication
      if not provided, requires 'id-token: write' permission). Required for GitLab CI.
    required: false
  input_path:
    description: "Path to the OpenAPI file."
    required: true
  config_path:
    description: "Path to the Stainless config file."
    required: false
  output_path:
    description: "Output path for the decorated OpenAPI spec."
  project_name:
    description: "Stainless project name."
    required: true
  commit_message:
    description: "Commit message to use in the commits in the SDK repo."
    required: false
  guess_config:
    description: "If true, renegerate the endpoints in the Stainless config file."
    required: false
    default: "false"
  branch:
    description: "If true, renegerate the endpoints in the Stainless config file."
    required: false
    default: "main"
