image: node:20-alpine

.checkout-pr-ref:
  script:
    - apk add --no-cache git
    - wget https://raw.githubusercontent.com/stainless-api/upload-openapi-spec-action/v1/dist/checkoutPRRef.js
    - node checkoutPRRef.js
  variables:
    HEAD_SHA: $CI_COMMIT_SHA
    BASE_SHA: $CI_MERGE_REQUEST_DIFF_BASE_SHA
