name: Stainless — Checkout PR base
description: Git checkout the merge base of a pull request
runs:
  using: node20
  main: ../dist/checkoutBase.js
inputs:
  oas_path:
    description: Path to your OpenAPI spec.
    required: true

  # We think it's unlikely you'll need to use non-default inputs for these:
  base_sha:
    description: >-
      The base SHA for the pull request. Used to create a base build.
    required: false
    default: ${{ github.event.pull_request.base.sha }}
  head_sha:
    description: >-
      The head SHA for the pull request. Used to get the OpenAPI spec and
      Stainless config for the preview build.
    required: false
    default: ${{ github.event.pull_request.head.sha }}
