image: node:20-alpine

.preview:
  # Required environment variables:
  # - STAINLESS_API_KEY: Stainless API key (required for GitLab CI)
  # - ORG: Stainless organization name
  # - PROJECT: Stainless project name
  # - OAS_PATH: Path to your OpenAPI spec
  #
  # Optional environment variables:
  # - CONFIG_PATH: Path to your Stainless config
  # - GITLAB_TOKEN: GitLab token for commenting on merge requests
  # - FAIL_ON: When to fail the job (defaults to "error")
  script:
    - apk add --no-cache git
    - wget https://raw.githubusercontent.com/stainless-api/upload-openapi-spec-action/v1/dist/preview.js
    - node preview.js
  variables:
    HEAD_SHA: $CI_COMMIT_SHA
    BASE_SHA: $CI_MERGE_REQUEST_DIFF_BASE_SHA
    BASE_REF: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
    BRANCH: "preview/${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME}"
    BASE_BRANCH: "preview/base/${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME}"
    DEFAULT_BRANCH: $CI_DEFAULT_BRANCH
    COMMIT_MESSAGE: $CI_MERGE_REQUEST_TITLE
    MR_NUMBER: $CI_MERGE_REQUEST_IID
    MAKE_COMMENT: true
