image: node:20-alpine

.preview:
  script:
    - apk add --no-cache git
    - wget https://raw.githubusercontent.com/stainless-api/upload-openapi-spec-action/v1/dist/preview.js
    - node preview.js
  variables:
    HEAD_SHA: $CI_COMMIT_SHA
    BASE_SHA: $CI_MERGE_REQUEST_DIFF_BASE_SHA
    BASE_REF: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
    BRANCH: "preview/${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME}"
    BASE_BRANCH: "preview/base/${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME}"
    DEFAULT_BRANCH: $CI_DEFAULT_BRANCH
    COMMIT_MESSAGE: $CI_MERGE_REQUEST_TITLE
    MR_NUMBER: $CI_MERGE_REQUEST_IID
    MAKE_COMMENT: true
