# Example GitHub Actions workflow for uploading OpenAPI spec to Stainless

name: Upload OpenAPI spec to Stainless

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  stainless:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: stainless-api/upload-openapi-spec-action@main
        with:
          # Required parameters
          stainless_api_key: ${{ secrets.STAINLESS_API_KEY }}
          input_path: "path/to/my-company-openapi.json"

          # Optional parameters
          project_name: "my-stainless-project"
          commit_message: "feat(api): my cool feature"
          guess_config: true
          # config_path: 'path/to/my-company.stainless.yaml'
          # output_path: 'path/to/my-company-openapi.documented.json'
          # branch: 'main'
