#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

echo "==> Running prettier --write"
./node_modules/.bin/prettier --write src 'examples/*.yml' '**/action.yml'

echo "==> Running eslint --fix"
./node_modules/.bin/eslint src --fix
